# All valid binary and unary operator combinations
# Auto-generated by scripts/generate_operator_tests.py

# ===== VALID BINARY OPERATIONS =====

v0_int_add_int: int = 1 + 1
v1_int_sub_int: int = 1 - 1
v2_int_mul_int: int = 1 * 1
v3_int_div_int: float = 1 / 1
v4_int_floordiv_int: int = 1 // 1
v5_int_mod_int: int = 1 % 1
v6_int_pow_int: int = 1 ** 1
v7_int_bitand_int: int = 1 & 1
v8_int_bitor_int: int = 1 | 1
v9_int_bitxor_int: int = 1 ^ 1
v10_int_lshift_int: int = 1 << 1
v11_int_rshift_int: int = 1 >> 1
v12_int_lt_int: bool = 1 < 1
v13_int_le_int: bool = 1 <= 1
v14_int_gt_int: bool = 1 > 1
v15_int_ge_int: bool = 1 >= 1
v16_int_add_float: float = 1 + 1.0
v17_int_sub_float: float = 1 - 1.0
v18_int_mul_float: float = 1 * 1.0
v19_int_div_float: float = 1 / 1.0
v20_int_floordiv_float: float = 1 // 1.0
v21_int_mod_float: float = 1 % 1.0
v22_int_pow_float: float = 1 ** 1.0
v23_int_lt_float: bool = 1 < 1.0
v24_int_le_float: bool = 1 <= 1.0
v25_int_gt_float: bool = 1 > 1.0
v26_int_ge_float: bool = 1 >= 1.0
v27_int_add_bool: int = 1 + True
v28_int_sub_bool: int = 1 - True
v29_int_mul_bool: int = 1 * True
v30_int_div_bool: float = 1 / True
v31_int_floordiv_bool: int = 1 // True
v32_int_mod_bool: int = 1 % True
v33_int_pow_bool: int = 1 ** True
v34_int_bitand_bool: int = 1 & True
v35_int_bitor_bool: int = 1 | True
v36_int_bitxor_bool: int = 1 ^ True
v37_int_lshift_bool: int = 1 << True
v38_int_rshift_bool: int = 1 >> True
v39_int_lt_bool: bool = 1 < True
v40_int_le_bool: bool = 1 <= True
v41_int_gt_bool: bool = 1 > True
v42_int_ge_bool: bool = 1 >= True
v43_int_mul_str: int = 1 * "hello"
v44_int_mul_bytes: int = 1 * b"hello"
v45_int_in_bytes: bool = 1 in b"hello"
v46_int_notin_bytes: bool = 1 not in b"hello"
v47_int_mul_list: int = 1 * [1, 2, 3]
v48_int_in_list: bool = 1 in [1, 2, 3]
v49_int_notin_list: bool = 1 not in [1, 2, 3]
v50_int_in_dict: bool = 1 in {"a": 1}
v51_int_notin_dict: bool = 1 not in {"a": 1}
v52_int_in_set: bool = 1 in {1, 2, 3}
v53_int_notin_set: bool = 1 not in {1, 2, 3}
v54_float_add_int: float = 1.0 + 1
v55_float_sub_int: float = 1.0 - 1
v56_float_mul_int: float = 1.0 * 1
v57_float_div_int: float = 1.0 / 1
v58_float_floordiv_int: float = 1.0 // 1
v59_float_mod_int: float = 1.0 % 1
v60_float_pow_int: float = 1.0 ** 1
v61_float_lt_int: bool = 1.0 < 1
v62_float_le_int: bool = 1.0 <= 1
v63_float_gt_int: bool = 1.0 > 1
v64_float_ge_int: bool = 1.0 >= 1
v65_float_add_float: float = 1.0 + 1.0
v66_float_sub_float: float = 1.0 - 1.0
v67_float_mul_float: float = 1.0 * 1.0
v68_float_div_float: float = 1.0 / 1.0
v69_float_floordiv_float: float = 1.0 // 1.0
v70_float_mod_float: float = 1.0 % 1.0
v71_float_pow_float: float = 1.0 ** 1.0
v72_float_lt_float: bool = 1.0 < 1.0
v73_float_le_float: bool = 1.0 <= 1.0
v74_float_gt_float: bool = 1.0 > 1.0
v75_float_ge_float: bool = 1.0 >= 1.0
v76_float_add_bool: float = 1.0 + True
v77_float_sub_bool: float = 1.0 - True
v78_float_mul_bool: float = 1.0 * True
v79_float_div_bool: float = 1.0 / True
v80_float_floordiv_bool: float = 1.0 // True
v81_float_mod_bool: float = 1.0 % True
v82_float_pow_bool: float = 1.0 ** True
v83_float_lt_bool: bool = 1.0 < True
v84_float_le_bool: bool = 1.0 <= True
v85_float_gt_bool: bool = 1.0 > True
v86_float_ge_bool: bool = 1.0 >= True
v87_float_in_list: bool = 1.0 in [1, 2, 3]
v88_float_notin_list: bool = 1.0 not in [1, 2, 3]
v89_float_in_dict: bool = 1.0 in {"a": 1}
v90_float_notin_dict: bool = 1.0 not in {"a": 1}
v91_float_in_set: bool = 1.0 in {1, 2, 3}
v92_float_notin_set: bool = 1.0 not in {1, 2, 3}
v93_bool_add_int: int = True + 1
v94_bool_sub_int: int = True - 1
v95_bool_mul_int: int = True * 1
v96_bool_div_int: float = True / 1
v97_bool_floordiv_int: int = True // 1
v98_bool_mod_int: int = True % 1
v99_bool_pow_int: int = True ** 1
v100_bool_bitand_int: int = True & 1
v101_bool_bitor_int: int = True | 1
v102_bool_bitxor_int: int = True ^ 1
v103_bool_lshift_int: int = True << 1
v104_bool_rshift_int: int = True >> 1
v105_bool_lt_int: bool = True < 1
v106_bool_le_int: bool = True <= 1
v107_bool_gt_int: bool = True > 1
v108_bool_ge_int: bool = True >= 1
v109_bool_add_float: float = True + 1.0
v110_bool_sub_float: float = True - 1.0
v111_bool_mul_float: float = True * 1.0
v112_bool_div_float: float = True / 1.0
v113_bool_floordiv_float: float = True // 1.0
v114_bool_mod_float: float = True % 1.0
v115_bool_pow_float: float = True ** 1.0
v116_bool_lt_float: bool = True < 1.0
v117_bool_le_float: bool = True <= 1.0
v118_bool_gt_float: bool = True > 1.0
v119_bool_ge_float: bool = True >= 1.0
v120_bool_add_bool: bool = True + True
v121_bool_sub_bool: bool = True - True
v122_bool_mul_bool: bool = True * True
v123_bool_div_bool: float = True / True
v124_bool_floordiv_bool: bool = True // True
v125_bool_mod_bool: bool = True % True
v126_bool_pow_bool: bool = True ** True
v127_bool_bitand_bool: bool = True & True
v128_bool_bitor_bool: bool = True | True
v129_bool_bitxor_bool: bool = True ^ True
v130_bool_lshift_bool: bool = True << True
v131_bool_rshift_bool: bool = True >> True
v132_bool_lt_bool: bool = True < True
v133_bool_le_bool: bool = True <= True
v134_bool_gt_bool: bool = True > True
v135_bool_ge_bool: bool = True >= True
v136_bool_mul_str: bool = True * "hello"
v137_bool_mul_bytes: bool = True * b"hello"
v138_bool_in_bytes: bool = True in b"hello"
v139_bool_notin_bytes: bool = True not in b"hello"
v140_bool_mul_list: bool = True * [1, 2, 3]
v141_bool_in_list: bool = True in [1, 2, 3]
v142_bool_notin_list: bool = True not in [1, 2, 3]
v143_bool_in_dict: bool = True in {"a": 1}
v144_bool_notin_dict: bool = True not in {"a": 1}
v145_bool_in_set: bool = True in {1, 2, 3}
v146_bool_notin_set: bool = True not in {1, 2, 3}
v147_str_mul_int: str = "hello" * 1
v148_str_mul_bool: str = "hello" * True
v149_str_add_str: str = "hello" + "hello"
v150_str_lt_str: bool = "hello" < "hello"
v151_str_le_str: bool = "hello" <= "hello"
v152_str_gt_str: bool = "hello" > "hello"
v153_str_ge_str: bool = "hello" >= "hello"
v154_str_in_str: bool = "hello" in "hello"
v155_str_notin_str: bool = "hello" not in "hello"
v156_str_mod_bytes: str = "hello" % b"hello"
v157_str_mod_list: str = "hello" % [1, 2, 3]
v158_str_in_list: bool = "hello" in [1, 2, 3]
v159_str_notin_list: bool = "hello" not in [1, 2, 3]
v160_str_mod_dict: str = "hello" % {"a": 1}
v161_str_in_dict: bool = "hello" in {"a": 1}
v162_str_notin_dict: bool = "hello" not in {"a": 1}
v163_str_in_set: bool = "hello" in {1, 2, 3}
v164_str_notin_set: bool = "hello" not in {1, 2, 3}
v165_bytes_mul_int: bytes = b"hello" * 1
v166_bytes_mul_bool: bytes = b"hello" * True
v167_bytes_add_bytes: bytes = b"hello" + b"hello"
v168_bytes_lt_bytes: bool = b"hello" < b"hello"
v169_bytes_le_bytes: bool = b"hello" <= b"hello"
v170_bytes_gt_bytes: bool = b"hello" > b"hello"
v171_bytes_ge_bytes: bool = b"hello" >= b"hello"
v172_bytes_in_bytes: bool = b"hello" in b"hello"
v173_bytes_notin_bytes: bool = b"hello" not in b"hello"
v174_bytes_mod_list: bytes = b"hello" % [1, 2, 3]
v175_bytes_in_list: bool = b"hello" in [1, 2, 3]
v176_bytes_notin_list: bool = b"hello" not in [1, 2, 3]
v177_bytes_mod_dict: bytes = b"hello" % {"a": 1}
v178_bytes_in_dict: bool = b"hello" in {"a": 1}
v179_bytes_notin_dict: bool = b"hello" not in {"a": 1}
v180_bytes_in_set: bool = b"hello" in {1, 2, 3}
v181_bytes_notin_set: bool = b"hello" not in {1, 2, 3}
v182_list_mul_int: list[int] = [1, 2, 3] * 1
v183_list_mul_bool: list[int] = [1, 2, 3] * True
v184_list_add_list: list[int] = [1, 2, 3] + [1, 2, 3]
v185_list_lt_list: bool = [1, 2, 3] < [1, 2, 3]
v186_list_le_list: bool = [1, 2, 3] <= [1, 2, 3]
v187_list_gt_list: bool = [1, 2, 3] > [1, 2, 3]
v188_list_ge_list: bool = [1, 2, 3] >= [1, 2, 3]
v189_list_in_list: bool = [1, 2, 3] in [1, 2, 3]
v190_list_notin_list: bool = [1, 2, 3] not in [1, 2, 3]
v191_dict_in_list: bool = {"a": 1} in [1, 2, 3]
v192_dict_notin_list: bool = {"a": 1} not in [1, 2, 3]
v193_dict_bitor_dict: dict[str, int] = {"a": 1} | {"a": 1}
v194_set_in_list: bool = {1, 2, 3} in [1, 2, 3]
v195_set_notin_list: bool = {1, 2, 3} not in [1, 2, 3]
v196_set_sub_set: set[int] = {1, 2, 3} - {1, 2, 3}
v197_set_bitand_set: set[int] = {1, 2, 3} & {1, 2, 3}
v198_set_bitor_set: set[int] = {1, 2, 3} | {1, 2, 3}
v199_set_bitxor_set: set[int] = {1, 2, 3} ^ {1, 2, 3}
v200_set_lt_set: bool = {1, 2, 3} < {1, 2, 3}
v201_set_le_set: bool = {1, 2, 3} <= {1, 2, 3}
v202_set_gt_set: bool = {1, 2, 3} > {1, 2, 3}
v203_set_ge_set: bool = {1, 2, 3} >= {1, 2, 3}
v204_set_in_set: bool = {1, 2, 3} in {1, 2, 3}
v205_set_notin_set: bool = {1, 2, 3} not in {1, 2, 3}
v206_none_in_list: bool = None in [1, 2, 3]
v207_none_notin_list: bool = None not in [1, 2, 3]
v208_none_in_dict: bool = None in {"a": 1}
v209_none_notin_dict: bool = None not in {"a": 1}
v210_none_in_set: bool = None in {1, 2, 3}
v211_none_notin_set: bool = None not in {1, 2, 3}

# ===== VALID UNARY OPERATIONS =====

u0_int_neg: int = -1
u1_int_pos: int = +1
u2_int_bitnot_val: int = 1
u2_int_bitnot: int = ~u2_int_bitnot_val
u3_float_neg: float = -1.0
u4_float_pos: float = +1.0
u5_bool_neg: int = -True
u6_bool_pos: int = +True
u7_bool_bitnot_val: bool = True
u7_bool_bitnot: int = ~u7_bool_bitnot_val

print("All valid operator tests passed!")
