# Valid ascii() calls
# Auto-generated by scripts/generate_tests.py

b0_ascii_int = ascii(1)
b1_ascii_float = ascii(1.0)
b2_ascii_bool = ascii(True)
b3_ascii_str = ascii("hello")
b4_ascii_bytes = ascii(b"hello")
b5_ascii_list = ascii([1, 2, 3])
b6_ascii_dict = ascii({"a": 1})
b7_ascii_set = ascii({1, 2, 3})
b8_ascii_none = ascii(None)

print("ascii() tests passed!")
