# Valid divmod() calls
# Auto-generated by scripts/generate_tests.py

b0_divmod_int_int = divmod(1, 1)
b1_divmod_int_float = divmod(1, 1.0)
b2_divmod_int_bool = divmod(1, True)
b3_divmod_float_int = divmod(1.0, 1)
b4_divmod_float_float = divmod(1.0, 1.0)
b5_divmod_float_bool = divmod(1.0, True)
b6_divmod_bool_int = divmod(True, 1)
b7_divmod_bool_float = divmod(True, 1.0)
b8_divmod_bool_bool = divmod(True, True)

print("divmod() tests passed!")
