# Valid min() calls
# Auto-generated by scripts/generate_tests.py

b0_min_str = min("hello")
b1_min_bytes = min(b"hello")
b2_min_list = min([1, 2, 3])
b3_min_dict = min({"a": 1})
b4_min_set = min({1, 2, 3})
b5_min_int_int = min(1, 1)
b6_min_int_float = min(1, 1.0)
b7_min_int_bool = min(1, True)
b8_min_float_int = min(1.0, 1)
b9_min_float_float = min(1.0, 1.0)
b10_min_float_bool = min(1.0, True)
b11_min_bool_int = min(True, 1)
b12_min_bool_float = min(True, 1.0)
b13_min_bool_bool = min(True, True)
b14_min_str_str = min("hello", "hello")
b15_min_bytes_bytes = min(b"hello", b"hello")
b16_min_list_list = min([1, 2, 3], [1, 2, 3])
b17_min_set_set = min({1, 2, 3}, {1, 2, 3})

print("min() tests passed!")
