# Valid round() calls
# Auto-generated by scripts/generate_tests.py

b0_round_int = round(1)
b1_round_float = round(1.0)
b2_round_bool = round(True)
b3_round_int_int = round(1, 1)
b4_round_int_bool = round(1, True)
b5_round_int_none = round(1, None)
b6_round_float_int = round(1.0, 1)
b7_round_float_bool = round(1.0, True)
b8_round_float_none = round(1.0, None)
b9_round_bool_int = round(True, 1)
b10_round_bool_bool = round(True, True)
b11_round_bool_none = round(True, None)

print("round() tests passed!")
