# Valid chr() calls
# Auto-generated by scripts/generate_tests.py

b0_chr_int = chr(1)
b1_chr_bool = chr(True)

# Print all variables
print("b0_chr_int:", b0_chr_int)
print("b1_chr_bool:", b1_chr_bool)

print("chr() tests passed!")
