# Valid hash() calls
# Auto-generated by scripts/generate_tests.py

b0_hash_int = hash(1)
b1_hash_float = hash(1.0)
b2_hash_bool = hash(True)
b3_hash_str = hash("hello")
b4_hash_bytes = hash(b"hello")
b5_hash_none = hash(None)

print("hash() tests passed!")
