# Valid max() calls
# Auto-generated by scripts/generate_tests.py

b0_max_str = max("hello")
b1_max_bytes = max(b"hello")
b2_max_list = max([1, 2, 3])
b3_max_dict = max({"a": 1})
b4_max_set = max({1, 2, 3})
b5_max_int_int = max(1, 1)
b6_max_int_float = max(1, 1.0)
b7_max_int_bool = max(1, True)
b8_max_float_int = max(1.0, 1)
b9_max_float_float = max(1.0, 1.0)
b10_max_float_bool = max(1.0, True)
b11_max_bool_int = max(True, 1)
b12_max_bool_float = max(True, 1.0)
b13_max_bool_bool = max(True, True)
b14_max_str_str = max("hello", "hello")
b15_max_bytes_bytes = max(b"hello", b"hello")
b16_max_list_list = max([1, 2, 3], [1, 2, 3])
b17_max_set_set = max({1, 2, 3}, {1, 2, 3})

print("max() tests passed!")
