# Valid range() calls
# Auto-generated by scripts/generate_tests.py

b0_range_int = range(1)
b1_range_bool = range(True)
b2_range_int_int = range(1, 1)
b3_range_int_bool = range(1, True)
b4_range_bool_int = range(True, 1)
b5_range_bool_bool = range(True, True)
b6_range_int_int_int = range(1, 1, 1)
b7_range_int_int_bool = range(1, 1, True)
b8_range_int_bool_int = range(1, True, 1)
b9_range_int_bool_bool = range(1, True, True)
b10_range_bool_int_int = range(True, 1, 1)
b11_range_bool_int_bool = range(True, 1, True)
b12_range_bool_bool_int = range(True, True, 1)
b13_range_bool_bool_bool = range(True, True, True)

print("range() tests passed!")
